<a href="https://colab.research.google.com/github/Saurabh1Barasiya/Pytorch/blob/master/pytorch_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
print(torch.__version__)

1.5.1+cu101


## Pytorch Tutorial
## Tensors Basics
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [8]:
import numpy as np 
a = [1,2,3,4]
arr = np.array(a)

In [9]:
print(arr)

[1 2 3 4]


In [10]:
arr.dtype

dtype('int64')

## Convert Numpy To Pytorch Tensors

In [13]:
tensors = torch.from_numpy(arr)
print(tensors)
print(type(tensors))

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


In [14]:
### Indexing similar to numpy
tensors[2]

tensor(3)

In [15]:
tensors[0:]

tensor([1, 2, 3, 4])

In [16]:
tensors[[1,2]]

tensor([2, 3])

In [17]:
#### Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]=100

In [20]:
print(tensors)
print(arr)
# so yaha hamne changes tensors me kiya the and changes  arr me bhi ho gaye to ye problem h

tensor([  1,   2,   3, 100])
[  1   2   3 100]


In [23]:
# to us  problem ko overkam karne ke  liye ham  torch.tensor ka use karege
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  1,   2,   3, 100])

In [24]:
tensor_arr[3] = 400

In [26]:
print(tensor_arr)
print(arr)
# so yaha changes nahi hue

tensor([  1,   2,   3, 400])
[  1   2   3 100]


In [27]:
print(tensor_arr.dtype)

torch.int64


In [28]:
#### zeros and ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [29]:
torch.ones(2,3,dtype=torch.int64)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [39]:
t = torch.tensor(np.arange(0,12).reshape(3,-1))
print(t,'\n',type(t),'\n',t.dtype)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) 
 <class 'torch.Tensor'> 
 torch.int64


In [40]:
t 

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [55]:
# here we extract values
print('Here we only get zeroth row ')
print(t[0])
print('\n'*2)

print('Here we get all the row and all the columns')
print(t[::])
print('\n'*2)

print('Here we get only frist row')
print(t[1,:])
print('\n'*2)

print('Here we get only last column')
print(t[:,[3]])
print('\n'*2)

print('Here we get frist element')
print(t[0][0])
print('\n'*2)

print('Here we get middle values')
print(t[0:2,1:3])

Here we only get zeroth row 
tensor([0, 1, 2, 3])



Here we get all the row and all the columns
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])



Here we get only frist row
tensor([4, 5, 6, 7])



Here we get only last column
tensor([[ 3],
        [ 7],
        [11]])



Here we get frist element
tensor(0)



Here we get middle values
tensor([[1, 2],
        [5, 6]])


## Arithmetic Operation

In [56]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [58]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [60]:
c = torch.zeros(3)
c

tensor([0., 0., 0.])

In [61]:
##### Some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [62]:
### tensor[7,9,11]
torch.add(a,b).sum()

tensor(27.)

## Dot Products and Mult Operations

In [63]:
x= torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [67]:
print(x.mul(y))
print("This is index vise multiplaction")
### 3*4+5*4+6*5

tensor([12., 20., 30.])
This is index vise multiplaction


In [70]:
print('dot multiplaction',x.dot(y))
print(3*4 + 5*4 + 6*5)

dot multiplaction tensor(62.)
62


In [71]:
###### MAtrix Multiplication
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [72]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [73]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [74]:
x@y

tensor([[55., 53.],
        [90., 92.]])