<a href="https://colab.research.google.com/github/Saurabh1Barasiya/Pytorch/blob/master/pytorch_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Back Propogation using pytorch


In [1]:
import torch

In [3]:
x = torch.tensor(4.0,requires_grad=True)
print(x)

tensor(4., requires_grad=True)


In [4]:
y = x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [5]:
#### Back propogation y=2*x
y.backward()

In [7]:
x.grad

tensor(8.)

In [9]:
lst=[[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input=torch.tensor(lst,requires_grad=True)
print(torch_input)

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)


In [17]:
##### y = x**3 + x**2  
##### y = 3x**2 + 2x
y = torch_input**3 + torch_input**2
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [18]:
y = 3*torch_input**2 + 2*torch_input
y

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]], grad_fn=<AddBackward0>)

In [11]:
z=y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [14]:
z.backward()

In [15]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])

# One more time

In [20]:
x = torch.tensor([[1,2,3],[1,2,3],[1,2,3]],requires_grad=True,dtype=torch.float)
x

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]], requires_grad=True)

In [25]:
### y = x**4 + x**2
### y = 4x**3 + 2x 

#  if i want to direct derivative of  frist y with respect to y.
print(4*x**3 + 2*x)

tensor([[  6.,  36., 114.],
        [  6.,  36., 114.],
        [  6.,  36., 114.]], grad_fn=<AddBackward0>)


In [30]:
y = x**4 + x**2
z = y.sum()
z.backward()


In [31]:
x.grad

tensor([[  6.,  36., 114.],
        [  6.,  36., 114.],
        [  6.,  36., 114.]])